services:
  blockchain-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
